#pragma once

#define WEAPONTYPE_UNARMED            0
#define WEAPONTYPE_BRASSKNUCKLE       1
#define WEAPONTYPE_SCREWDRIVER        2
#define WEAPONTYPE_GOLFCLUB           3
#define WEAPONTYPE_NIGHTSTICK         4
#define WEAPONTYPE_KNIFE              5
#define WEAPONTYPE_BASEBALLBAT        6
#define WEAPONTYPE_HAMMER             7
#define WEAPONTYPE_CLEAVER            8
#define WEAPONTYPE_MACHETE            9
#define WEAPONTYPE_KATANA            10
#define WEAPONTYPE_CHAINSAW          11
#define WEAPONTYPE_GRENADE           12
#define WEAPONTYPE_DETONATOR_GRENADE 13
#define WEAPONTYPE_TEARGAS           14
#define WEAPONTYPE_MOLOTOV           15
#define WEAPONTYPE_ROCKET            16
#define WEAPONTYPE_PISTOL            17
#define WEAPONTYPE_PYTHON            18
#define WEAPONTYPE_SHOTGUN           19
#define WEAPONTYPE_SPAS12_SHOTGUN    20
#define WEAPONTYPE_STUBBY_SHOTGUN    21
#define WEAPONTYPE_TEC9              22
#define WEAPONTYPE_UZI               23
#define WEAPONTYPE_SILENCED_INGRAM   24
#define WEAPONTYPE_MP5               25
#define WEAPONTYPE_M16               26
#define WEAPONTYPE_CHAINGUN          27
#define WEAPONTYPE_SNIPERRIFLE       28
#define WEAPONTYPE_LASERSCOPE        29
#define WEAPONTYPE_ROCKETLAUNCHER    30
#define WEAPONTYPE_FLAMETHROWER      31
#define WEAPONTYPE_M60               32
#define WEAPONTYPE_MINIGUN           33
#define WEAPONTYPE_DETONATOR         34
#define WEAPONTYPE_HELICANNON        35
#define WEAPONTYPE_CAMERA            36
#define WEAPONTYPE_PAD37             37
#define WEAPONTYPE_ARMOUR            38
#define WEAPONTYPE_RAMMEDBYCAR       39
#define WEAPONTYPE_RUNOVERBYCAR      40
#define WEAPONTYPE_EXPLOSION         41
#define WEAPONTYPE_UZI_DRIVEBY       42
#define WEAPONTYPE_DROWNING          43
#define WEAPONTYPE_FALL              44
#define WEAPONTYPE_UNIDENTIFIED      45
#define WEAPONTYPE_ANYMELEE          46
#define WEAPONTYPE_ANYWEAPON         47
